version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mvc
    restart: always
    volumes:
      - ./mvc:/var/www
  nginx:
    image: nginx:1.21.6-alpine
    container_name: nginx
    restart: always
    ports:
      - "8006:80"
    volumes:
      - ./mvc:/var/www
      - ./nginx:/etc/nginx/conf.d
  db:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
    ports:
      - 3308:3306
    volumes:
      - mysql:/var/lib/mysql
volumes:
  mysql: