version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mvc
    restart: always
    volumes:
      - ./mvc:/var/www
  nginx:
    image: nginx:1.21.6-alpine
    container_name: nginx
    restart: always
    ports:
      - "8006:80"
    volumes:
      - ./mvc:/var/www
      - ./nginx:/etc/nginx/conf.d